package com.miklesam.dotamanager.room

import com.miklesam.dotamanager.datamodels.Heroes
import com.miklesam.dotamanager.datamodels.Player

class PlayersList {

    companion object {
        const val CATEGORY_IMAGE_DIR = "android.resource://com.miklesam.dotamanager/drawable/"
        val VP = listOf(
            Player(
                CATEGORY_IMAGE_DIR + "russia4020",
                "Solo",
                "Alexey Berezin",
                "5",
                "105000",
                CATEGORY_IMAGE_DIR + "solo_face",
                77,
                87,
                83,
                82,
                80,
                85,
                77,
                79,
                86,
                90,
                Heroes.DISRUPTOR.id,
                Heroes.BANE.id,
                Heroes.SHADOW_DEMON.id
            ),
            Player(
                CATEGORY_IMAGE_DIR + "kirgistan4020",
                "Zayac",
                "Bakyt Emilzhanov",
                "4",
                "80000",
                CATEGORY_IMAGE_DIR + "zayc_face",
                80,
                78,
                85,
                84,
                80,
                79,
                80,
                81,
                81,
                79,
                Heroes.ELDER_TITAN.id,
                Heroes.TREANT.id,
                Heroes.NYX.id
            ),
            Player(
                CATEGORY_IMAGE_DIR + "ukraine4020",
                "Resolut1on",
                "Roman Fominok",
                "3",
                "75000",
                CATEGORY_IMAGE_DIR + "resolution_face",
                78,
                80,
                78,
                79,
                80,
                82,
                83,
                82,
                80,
                85,
                Heroes.BEASTMASTER.id,
                Heroes.PUCK.id,
                Heroes.CENTAUR.id
            ),
            Player(
                CATEGORY_IMAGE_DIR + "russia4020",
                "No[o]ne",
                "Vladimir Minenko",
                "2",
                "85000",
                CATEGORY_IMAGE_DIR + "noone_face",
                84,
                76,
                79,
                83,
                80,
                81,
                87,
                84,
                78,
                79,
                Heroes.DK.id,
                Heroes.INVOKER.id,
                Heroes.STORM_SPIRIT.id
            ),
            Player(
                CATEGORY_IMAGE_DIR + "russia4020",
                "Cooman",
                "Zaur Shakhmurzaev",
                "1",
                "60000",
                CATEGORY_IMAGE_DIR + "cooman_face",
                78,
                76,
                78,
                79,
                80,
                83,
                81,
                83,
                80,
                83,
                Heroes.JUGGERNAUT.id,
                Heroes.TERROBLADE.id,
                Heroes.TEMPLAR_ASSASIN.id
            )

        )
        val NaVi = listOf(
            Player(
                CATEGORY_IMAGE_DIR + "russia4020",
                "illias",
                "Ilyas Ganeev",
                "5",
                "55000",
                CATEGORY_IMAGE_DIR + "illias_face",
                77,
                75,
                79,
                79,
                80,
                77,
                79,
                79,
                77,
                81,
                Heroes.CM.id,
                Heroes.UNDYING.id,
                Heroes.AA.id
            ),
            Player(
                CATEGORY_IMAGE_DIR + "ukraine4020",
                "CemaTheSlayer",
                "Semen Cryvulya",
                "4",
                "55000",
                CATEGORY_IMAGE_DIR + "cema_face",
                79,
                78,
                82,
                81,
                80,
                78,
                81,
                79,
                78,
                82,
                Heroes.DISRUPTOR.id,
                Heroes.DAZZLE.id,
                Heroes.WITCH_DOCTOR.id
            ),
            Player(
                CATEGORY_IMAGE_DIR + "russia4020",
                "9pasha",
                "Pavel Khvastunov",
                "3",
                "75000",
                CATEGORY_IMAGE_DIR + "pasha_face",
                77,
                80,
                79,
                81,
                80,
                82,
                80,
                83,
                82,
                88,
                Heroes.DARKSEER.id,
                Heroes.MAGNUS.id,
                Heroes.CENTAUR.id
            ),
            Player(
                CATEGORY_IMAGE_DIR + "israel",
                "MagicaL",
                "Idan Vardanian",
                "2",
                "70000",
                CATEGORY_IMAGE_DIR + "magical_face",
                80,
                76,
                78,
                75,
                80,
                83,
                90,
                79,
                79,
                79,
                Heroes.TEMPLAR_ASSASIN.id,
                Heroes.RAZOR.id,
                Heroes.TINKER.id
            ),
            Player(
                CATEGORY_IMAGE_DIR + "ukraine4020",
                "Crystallize",
                "Vladislav Krystanek",
                "1",
                "70000",
                CATEGORY_IMAGE_DIR + "cristallyze_face",
                79,
                77,
                77,
                80,
                80,
                81,
                88,
                81,
                78,
                78,
                Heroes.LIFESTEALER.id,
                Heroes.FACELESS_VOID.id,
                Heroes.SVEN.id
            )
        )
        val Gambit = listOf(Player(
            CATEGORY_IMAGE_DIR + "kirgistan4020",
            "Dream",
            "Kiyalbek Tayirov",
            "1",
            "17000",
            CATEGORY_IMAGE_DIR + "dream_face",
            85,
            74,
            76,
            83,
            76,
            70,
            84,
            81,
            60,
            69,
            Heroes.JUGGERNAUT.id,
            Heroes.TERROBLADE.id,
            Heroes.MORPHLING.id
        ),
            Player(
                CATEGORY_IMAGE_DIR + "russia4020",
                "gpk",
                "Danil Skutin",
                "2",
                "17000",
                CATEGORY_IMAGE_DIR + "gpk_face",
                85,
                74,
                76,
                83,
                76,
                70,
                84,
                81,
                60,
                69,
                Heroes.EMBER.id,
                Heroes.SHADOW_FIEND.id,
                Heroes.TEMPLAR_ASSASIN.id
            ),
            Player(
                CATEGORY_IMAGE_DIR + "russia4020",
                "Shachlo",
                "Maxim Abramovskikh",
                "3",
                "17000",
                CATEGORY_IMAGE_DIR + "shachlo_face",
                85,
                74,
                76,
                83,
                76,
                70,
                84,
                81,
                60,
                69,
                Heroes.AXE.id,
                Heroes.BATHRIDER.id,
                Heroes.LONE_DRUID.id
            ),
            Player(
                CATEGORY_IMAGE_DIR + "kazahstan4020",
                "XSvamp1Re",
                "Danial Alibaev",
                "4",
                "17000",
                CATEGORY_IMAGE_DIR + "xsvampire_face",
                85,
                74,
                76,
                83,
                76,
                70,
                84,
                81,
                60,
                69,
                Heroes.TUSK.id,
                Heroes.EARTH_SPIRIT.id,
                Heroes.EARTH_SHAKER.id
            ),
            Player(
                CATEGORY_IMAGE_DIR + "belarus4020",
                "fng",
                "Artsiom Barshak",
                "5",
                "17000",
                CATEGORY_IMAGE_DIR + "fng_face",
                85,
                74,
                76,
                83,
                76,
                70,
                84,
                81,
                60,
                69,
                Heroes.BANE.id,
                Heroes.VENGEFUL.id,
                Heroes.TREANT.id
            ))
        val Secret= listOf(Player(
            CATEGORY_IMAGE_DIR + "finland",
            "Matumbaman",
            "Lasse Urpalainen",
            "1",
            "17000",
            CATEGORY_IMAGE_DIR + "matumbaman_face",
            85,
            74,
            76,
            83,
            76,
            70,
            84,
            81,
            60,
            69,
            Heroes.LONE_DRUID.id,
            Heroes.LYCAN.id,
            Heroes.BROODMOTHER.id
        ),
            Player(
                CATEGORY_IMAGE_DIR + "poland",
                "Nisha",
                "Michał Jankowski",
                "2",
                "17000",
                CATEGORY_IMAGE_DIR + "nisha_face",
                85,
                74,
                76,
                83,
                76,
                70,
                84,
                81,
                60,
                69,
                Heroes.TERROBLADE.id,
                Heroes.ARC_WARDEN.id,
                Heroes.MORPHLING.id
            ),
            Player(
                CATEGORY_IMAGE_DIR + "sweden",
                "Zai",
                "Ludwig Wåhlberg",
                "3",
                "17000",
                CATEGORY_IMAGE_DIR + "zai_face",
                85,
                74,
                76,
                83,
                76,
                70,
                84,
                81,
                60,
                69,
                Heroes.ENIGMA.id,
                Heroes.BATHRIDER.id,
                Heroes.DARKSEER.id
            ),
            Player(
                CATEGORY_IMAGE_DIR + "jordan",
                "Yapzor",
                "Yazied Jaradat",
                "4",
                "17000",
                CATEGORY_IMAGE_DIR + "yapzor_face",
                85,
                74,
                76,
                83,
                76,
                70,
                84,
                81,
                60,
                69,
                Heroes.RUBICK.id,
                Heroes.EARTH_SHAKER.id,
                Heroes.ENIGMA.id
            ),
            Player(
                CATEGORY_IMAGE_DIR + "estonia",
                "Puppey",
                "Clement Ivanov",
                "5",
                "17000",
                CATEGORY_IMAGE_DIR + "puppey_face",
                85,
                74,
                76,
                83,
                76,
                70,
                84,
                81,
                60,
                69,
                Heroes.CHEN.id,
                Heroes.ENCHANTRESS.id,
                Heroes.BOUNTY.id
            ))
        val ViciGaming= listOf(Player(
            CATEGORY_IMAGE_DIR + "china",
            "Paparazi",
            "Zhang Chengjun",
            "1",
            "17000",
            CATEGORY_IMAGE_DIR + "paparazi_face",
            85,
            74,
            76,
            83,
            76,
            70,
            84,
            81,
            60,
            69,
            Heroes.LIFESTEALER.id,
            Heroes.SVEN.id,
            Heroes.SLARK.id
        ),
            Player(
                CATEGORY_IMAGE_DIR + "china",
                "Ori",
                "Zeng Jiaoyang",
                "2",
                "17000",
                CATEGORY_IMAGE_DIR + "ori_face",
                85,
                74,
                76,
                83,
                76,
                70,
                84,
                81,
                60,
                69,
                Heroes.TEMPLAR_ASSASIN.id,
                Heroes.STORM_SPIRIT.id,
                Heroes.SHADOW_FIEND.id
            ),
            Player(
                CATEGORY_IMAGE_DIR + "china",
                "Yang",
                "Zhou Haiyang",
                "3",
                "17000",
                CATEGORY_IMAGE_DIR + "yang_face",
                85,
                74,
                76,
                83,
                76,
                70,
                84,
                81,
                60,
                69,
                Heroes.CLOCKWERK.id,
                Heroes.DARKSEER.id,
                Heroes.BEASTMASTER.id
            ),
            Player(
                CATEGORY_IMAGE_DIR + "china",
                "Pyw",
                "Xiong Jiahan",
                "4",
                "17000",
                CATEGORY_IMAGE_DIR + "pyw_face",
                85,
                74,
                76,
                83,
                76,
                70,
                84,
                81,
                60,
                69,
                Heroes.LESHRAC.id,
                Heroes.SAND_KING.id,
                Heroes.RUBICK.id
            ),
            Player(
                CATEGORY_IMAGE_DIR + "china",
                "Dy",
                "Ding Cong",
                "5",
                "17000",
                CATEGORY_IMAGE_DIR + "dy_face",
                85,
                74,
                76,
                83,
                76,
                70,
                84,
                81,
                60,
                69,
                Heroes.EARTH_SPIRIT.id,
                Heroes.MONKEY_KING.id,
                Heroes.CLOCKWERK.id
            ))
        val EG= listOf(Player(
            CATEGORY_IMAGE_DIR + "kanada",
            "Arteezy",
            "Artour Babaev",
            "1",
            "17000",
            CATEGORY_IMAGE_DIR + "artezy_face",
            85,
            74,
            76,
            83,
            76,
            70,
            84,
            81,
            60,
            69,
            Heroes.DROW.id,
            Heroes.LYCAN.id,
            Heroes.NAGA.id
        ),
            Player(
                CATEGORY_IMAGE_DIR + "phillipines",
                "Abed",
                "Abed Yusop",
                "2",
                "17000",
                CATEGORY_IMAGE_DIR + "abed_face",
                85,
                74,
                76,
                83,
                76,
                70,
                84,
                81,
                60,
                69,
                Heroes.MEEPO.id,
                Heroes.INVOKER.id,
                Heroes.TINKER.id
            ),
            Player(
                CATEGORY_IMAGE_DIR + "russia4020",
                "Ramzes",
                "Roman Kushnarev",
                "3",
                "17000",
                CATEGORY_IMAGE_DIR + "ramzes_face",
                85,
                74,
                76,
                83,
                76,
                70,
                84,
                81,
                60,
                69,
                Heroes.TIMBERSAW.id,
                Heroes.OMNIKNIGHT.id,
                Heroes.BEASTMASTER.id
            ),
            Player(
                CATEGORY_IMAGE_DIR + "denmark",
                "Cr1t",
                "Andreas Nielsen",
                "4",
                "17000",
                CATEGORY_IMAGE_DIR + "cr1t_face",
                85,
                74,
                76,
                83,
                76,
                70,
                84,
                81,
                60,
                69,
                Heroes.RUBICK.id,
                Heroes.EARTH_SPIRIT.id,
                Heroes.DARK_WILLOW.id
            ),
            Player(
                CATEGORY_IMAGE_DIR + "israel",
                "Fly",
                "Tal Aizik",
                "5",
                "17000",
                CATEGORY_IMAGE_DIR + "fly_face",
                85,
                74,
                76,
                83,
                76,
                70,
                84,
                81,
                60,
                69,
                Heroes.DAZZLE.id,
                Heroes.CM.id,
                Heroes.DISRUPTOR.id
            ))
        val Alliance = listOf(Player(
            CATEGORY_IMAGE_DIR + "bulgaria",
            "Nikobaby",
            "Nikolay Nikolov",
            "1",
            "17000",
            CATEGORY_IMAGE_DIR + "nikobaby_face",
            85,
            74,
            76,
            83,
            76,
            70,
            84,
            81,
            60,
            69,
            Heroes.SLARK.id,
            Heroes.ANTIMAGE.id,
            Heroes.QOP.id
        ),
            Player(
                CATEGORY_IMAGE_DIR + "sweden",
                "Limp",
                "Linus Blomdin",
                "2",
                "17000",
                CATEGORY_IMAGE_DIR + "limp_face",
                85,
                74,
                76,
                83,
                76,
                70,
                84,
                81,
                60,
                69,
                Heroes.PUCK.id,
                Heroes.TINY.id,
                Heroes.TEMPLAR_ASSASIN.id
            ),
            Player(
                CATEGORY_IMAGE_DIR + "israel",
                "33",
                "Neta Shapira",
                "3",
                "17000",
                CATEGORY_IMAGE_DIR + "the_koon_face",
                85,
                74,
                76,
                83,
                76,
                70,
                84,
                81,
                60,
                69,
                Heroes.BATHRIDER.id,
                Heroes.DARKSEER.id,
                Heroes.LC.id
            ),
            Player(
                CATEGORY_IMAGE_DIR + "sweden",
                "Handsken",
                "Simon Haag",
                "4",
                "17000",
                CATEGORY_IMAGE_DIR + "handsken_face",
                85,
                74,
                76,
                83,
                76,
                70,
                84,
                81,
                60,
                69,
                Heroes.IO.id,
                Heroes.DISRUPTOR.id,
                Heroes.CHEN.id
            ),
            Player(
                CATEGORY_IMAGE_DIR + "germany",
                "Fata",
                "Adrian Trinks",
                "5",
                "17000",
                CATEGORY_IMAGE_DIR + "fata_face",
                85,
                74,
                76,
                83,
                76,
                70,
                84,
                81,
                60,
                69,
                Heroes.JAKIRO.id,
                Heroes.OGREMAGI.id,
                Heroes.UNDYING.id
            ))
        val TNC= listOf(Player(
            CATEGORY_IMAGE_DIR + "phillipines",
            "Gabbi",
            "Kim Villafuerte",
            "1",
            "17000",
            CATEGORY_IMAGE_DIR + "gabbi_face",
            85,
            74,
            76,
            83,
            76,
            70,
            84,
            81,
            60,
            69,
            Heroes.JUGGERNAUT.id,
            Heroes.SVEN.id,
            Heroes.WIVER.id
        ),
            Player(
                CATEGORY_IMAGE_DIR + "phillipines",
                "Armel",
                "Armel Paul Tabios",
                "2",
                "17000",
                CATEGORY_IMAGE_DIR + "armel_face",
                85,
                74,
                76,
                83,
                76,
                70,
                84,
                81,
                60,
                69,
                Heroes.OD.id,
                Heroes.TEMPLAR_ASSASIN.id,
                Heroes.INVOKER.id
            ),
            Player(
                CATEGORY_IMAGE_DIR + "australia",
                "kpii",
                "Damien Chok",
                "3",
                "17000",
                CATEGORY_IMAGE_DIR + "kpii_face",
                85,
                74,
                76,
                83,
                76,
                70,
                84,
                81,
                60,
                69,
                Heroes.ENIGMA.id,
                Heroes.OMNIKNIGHT.id,
                Heroes.NAGA.id
            ),
            Player(
                CATEGORY_IMAGE_DIR + "phillipines",
                "Tims",
                "Timothy Randrup",
                "4",
                "17000",
                CATEGORY_IMAGE_DIR + "tims_face",
                85,
                74,
                76,
                83,
                76,
                70,
                84,
                81,
                60,
                69,
                Heroes.EARTH_SPIRIT.id,
                Heroes.EARTH_SHAKER.id,
                Heroes.NYX.id
            ),
            Player(
                CATEGORY_IMAGE_DIR + "southkorea",
                "March",
                "Park Tae-won",
                "5",
                "17000",
                CATEGORY_IMAGE_DIR + "march_face",
                85,
                74,
                76,
                83,
                76,
                70,
                84,
                81,
                60,
                69,
                Heroes.SPIRIT_BREAKER.id,
                Heroes.WARLOCK.id,
                Heroes.UNDYING.id
            ))
        val Liquid= listOf(Player(
            CATEGORY_IMAGE_DIR + "sweden",
            "miCKe",
            "Michael Vu",
            "1",
            "17000",
            CATEGORY_IMAGE_DIR + "micke_face",
            85,
            74,
            76,
            83,
            76,
            70,
            84,
            81,
            60,
            69,
            Heroes.MIRANA.id,
            Heroes.EMBER.id,
            Heroes.MORPHLING.id
        ),
            Player(
                CATEGORY_IMAGE_DIR + "germany",
                "qojqva",
                "Maximilian Bröcker",
                "2",
                "17000",
                CATEGORY_IMAGE_DIR + "qojqva_face",
                85,
                74,
                76,
                83,
                76,
                70,
                84,
                81,
                60,
                69,
                Heroes.LONE_DRUID.id,
                Heroes.NATURES_PROPHET.id,
                Heroes.INVOKER.id
            ),
            Player(
                CATEGORY_IMAGE_DIR + "sweden",
                "Boxi",
                "Samuel Svahn",
                "3",
                "17000",
                CATEGORY_IMAGE_DIR + "boxi_face",
                85,
                74,
                76,
                83,
                76,
                70,
                84,
                81,
                60,
                69,
                Heroes.BREWMASTER.id,
                Heroes.BEASTMASTER.id,
                Heroes.EARTH_SHAKER.id
            ),
            Player(
                CATEGORY_IMAGE_DIR + "norvay",
                "Taiga",
                "Tommy Le",
                "4",
                "17000",
                CATEGORY_IMAGE_DIR + "taiga_face",
                85,
                74,
                76,
                83,
                76,
                70,
                84,
                81,
                60,
                69,
                Heroes.EARTH_SPIRIT.id,
                Heroes.CHEN.id,
                Heroes.IO.id
            ),
            Player(
                CATEGORY_IMAGE_DIR + "sweden",
                "iNSaNiA",
                "Aydin Sarkohi",
                "5",
                "17000",
                CATEGORY_IMAGE_DIR + "insania_face",
                85,
                74,
                76,
                83,
                76,
                70,
                84,
                81,
                60,
                69,
                Heroes.RUBICK.id,
                Heroes.CM.id,
                Heroes.PHOENIX.id
            ))
    }
}
